### ISSUE TITLE
Validation jobs should run on the jobs node group

### ISSUE THREAD

**Issue by maxgio92** [falcosecurity/test-infra#1148]
**Feature request**

Validation jobs should run on the jobs node group.

They should be configured with appropriate selection and tolerations, at `PodSpec`-level. E.g.:

```
      tolerations:
      - key: "Archtype"
        operator: "Equal"
        value: "arm"
        effect: "NoSchedule"
      - key: "Availability"
        operator: "Equal"
        value: "SingleAZ"
        effect: "NoSchedule"
      nodeSelector:
        Archtype: "arm"
        Application: "jobs"
```

**Additional context**

Otherwise, those jobs would run on the Prow-dedicated node group.

For examples, take a look at https://github.com/falcosecurity/test-infra/blob/master/config/jobs/build-drivers/.
