### ISSUE TITLE
Test pods deleted unexpectedly

### ISSUE THREAD

**Issue by maxgio92** [falcosecurity/test-infra#404]
**Describe the bug**

Some `Prowjob` testing pods are unexpectedly killed and deleted.

**How to reproduce it**

For instance, after 10h 30m of the `build-drivers-ubuntu-aws-presubmit` `ProwJob` running ([here](https://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_test-infra/398/build-drivers-ubuntu-aws-presubmit/1396284329402830848) an example).

**Expected behaviour**

The testing container should complete his work and exit with 0 autonomously as for its command, and the Pod only garbage collected then.

**Case analysis**
[This example](https://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_test-infra/398/build-drivers-ubuntu-aws-presubmit/1396284329402830848) of a `build-drivers-ubuntu-aws-presubmit` `ProwJob` run is taken into consideration, to analyze the incident.
This is the `status` field of the related `ProwJob` Kubernetes object:
```
 kind: ProwJob
 [...]
 status:
    build_id: "1396284329402830848"
    completionTime: "2021-05-23T12:34:35Z"
    description: Pod got deleted unexpectedly
    pendingTime: "2021-05-23T01:58:20Z"
    pod_name: 59581435-bb6a-11eb-ad79-86d36086ea2e
    prev_report_states:
      gcsk8sreporter: error
      gcsreporter: error
      github-reporter: error
    startTime: "2021-05-23T01:58:20Z"
    state: error
    url: http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_test-infra/398/build-drivers-ubuntu-aws-presubmit/1396284329402830848
```

In turn, the `ProwJob` pod containers seems have been killed, before being deleted:

![image](https://user-images.githubusercontent.com/7593929/119378482-9be1b280-bcbe-11eb-8709-e68119f49bd7.png)

In the same time range all of these presubmit jobs completed with success:

![image](https://user-images.githubusercontent.com/7593929/119379470-cf710c80-bcbf-11eb-9f65-a802a4e9bf55.png)

At the time of the failure of the `build-drivers-ubuntu-aws-presubmit` job no `update-jobs-pr` job seems to have overlapped so that the `build-drivers-ubuntu-aws-presubmit` job would have been re-created with the updated configurations:

![image](https://user-images.githubusercontent.com/7593929/119379662-0e06c700-bcc0-11eb-9544-cea804b2b660.png)

Furthermore, the resource used by the testing pods seems to be coherent with what is requested (and limited), but a dig into it is worth.

**Environment**

test-infra

**Mitigations**

A possible mitigation and maybe good practice too could be to:
- further split drivers build jobs (e.g. per Kernel version)
- set resources on each Prow microservice (requests at least)
